name: Reusable workflow example

on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string

jobs:
  Set-ENV:
    runs-on:  ubuntu-latest
    environment:
      name:  ${{ inputs.environment-name }}
    outputs:
      connecteda-app-client-id: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
      connected-app-client-secret: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
      test-secret22: ${{ secrets.TEST_SECRET22 }}

    
    steps:
    - name: Set up secret file
      run: |
        echo "Step1"
        echo $APP_NAME
        echo $ENV_NAME
        echo $DEPLOY_TARGET
        echo $DEPLOY_TARGET_TYPE
        echo $CONNECTED_APP_CLIENT_ID  | sed 's/./& /g'
        echo $CONNECTED_APP_CLIENT_SECRET | sed 's/./& /g'
        echo $TEST_SECRET22 | sed 's/./& /g'

  job2:
    needs: [  Set-ENV ]
    runs-on:  ubuntu-latest
    #runs-on: rhel8
    env:
      APP_NAME: ${{ vars.APP_NAME }}
      ENV_NAME: ${{ vars.ENV_NAME }}
      DEPLOY_TARGET: ${{ vars.DEPLOY_TARGET }}
      DEPLOY_TARGET_TYPE: ${{ vars.DEPLOY_TARGET_TYPE }}
      CONNECTED_APP_CLIENT_ID: ${{ needs.Set-ENV.outputs.connected-app-client-id }}
      CONNECTED_APP_CLIENT_SECRET: ${{ needs.Set-ENV.outputs.connected-app-client-secret }}
      TEST_SECRET22: ${{ secrets.TEST_SECRET22 }}
    environment:
      name:  ${{ inputs.environment-name }}
    steps:
    - name: Step 2
      run: |
        echo "Step2"
        echo $APP_NAME
        echo $ENV_NAME
        echo $DEPLOY_TARGET
        echo $DEPLOY_TARGET_TYPE
        echo $CONNECTED_APP_CLIENT_ID  | sed 's/./& /g'
        echo $CONNECTED_APP_CLIENT_SECRET  | sed 's/./& /g'
        echo $TEST_SECRET22  | sed 's/./& /g'
        ls -la
        ./deploy.sh



